### ISSUE TITLE
Text summarization by abstractive methods

### ISSUE THREAD

**Issue by kanishk-23** [parth126/IT550#1]
### Title

Text summarization by abstractive methods

### Team Name

Fantastic 4

### Email

202103005@daiict.ac.in

### Team Member 1 Name

Kanishk Dad

### Team Member 1 Id

202103005@daiict.ac.in

### Team Member 2 Name

Dhyey Patel

### Team Member 2 Id

202103053@daiict.ac.in

### Team Member 3 Name

Dhruv Limbad

### Team Member 3 Id

202101263@daiict.ac.in

### Team Member 4 Name

Aarzoo Khambhoo

### Team Member 4 Id

202103026@daiict.ac.in

### Category

Reproducibility

### Problem Statement

We will be working on abstractive text summarization of news articles and will try to optimize it.

### Evaluation Strategy

ROUGE score

### Dataset

https://huggingface.co/datasets/abisee/cnn_dailymail

### Resources

chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://arxiv.org/pdf/1611.04230v1

**Comment by parth126** [comment]
- Suggested using a NN based summarization instead of RL 
- Reference: Get To The Point: Summarization with Pointer-Generator Networks (https://github.com/abisee/pointer-generator)

**Comment by parth126** [comment]
The project will be of reproducibility category
The group will choose between summarunner and pointer generator network

**Comment by kanishk-23** [comment]
closes #1

**Comment by parth126** [comment]
@kanishk-23 you need to add the entries to the project-list.md file
please read the instructions and do the needful.
