### ISSUE TITLE
Faster Maximum Inner Product Search in High Dimensions [Reproducibility]

### ISSUE THREAD

**Issue by ExhoParth** [parth126/IT550#12]
### Title
**Faster Maximum Inner Product Search in High Dimensions [Reproducibility]**

### Team Name

VectorForge

### Email

202311033@daiict.ac.in

### Team Member 1 Name

Parth Borad

### Team Member 1 Id

202311033

### Team Member 2 Name

Sarthak Vadher

### Team Member 2 Id

202311040

### Team Member 3 Name

Dhairya Dave

### Team Member 3 Id

202311011

### Team Member 4 Name

Viraj Prajapati

### Team Member 4 Id

202311069

### Category

Reproducibility

### Problem Statement
In the era of large-scale recommendation systems, document retrieval, and question-answering, efficient and accurate search techniques are essential. The Maximum Inner Product Search (MIPS) problem, a key operation in vector database systems, is used to find the item that maximizes the inner product with a given query. This operation is computationally expensive in high-dimensional vector spaces, which necessitates more efficient methods.

In 2024, a group of researchers presented a novel approach for 'Faster Maximum Inner Product Search in High Dimensions' at the International Conference on Machine Learning (ICML). Their work introduces a new framework to reduce computational cost and improve search speed. This project aims to reproduce the methodology outlined in the paper and implement our own version to gain deeper insights, which will ultimately help in designing efficient document retrieval systems from vector database.

### Evaluation Strategy

The evaluation focuses on the trade-off between accuracy and speed, comparing the proposed algorithm against eight baseline MIPS algorithms: LSH-MIPS, H2-ALSH-MIPS, NEQ-MIPS, PCA-MIPS, BoundedME, Greedy-MIPS, HNSW-MIPS, and NAPG-MIPS. Additionally, the sample complexity of the algorithms is analyzed.

### Dataset
* Synthetic Dataset
#### Real-world Datasets
* [Netflix Price Data](https://www.kaggle.com/datasets/netflix-inc/netflix-prize-data)
* [MovieLens 20M Dataset](https://www.kaggle.com/datasets/grouplens/movielens-20m-dataset)
#### Additional Datasets
* [Sift-1M](https://frankie-yanfeng.github.io/2019/02/18/sift-1M-dataset-and-ANN-2019/)
* [CryptoPairs](https://www.kaggle.com/datasets/tencars/392-crypto-currency-pairs-at-minute-resolution)

### Resources

Paper: [Faster Maximum Inner Product Search in High Dimensions](https://icml.cc/virtual/2024/poster/34542) ICML 2024
[MIPS Wikipedia](https://en.wikipedia.org/wiki/Maximum_inner-product_search)
[MIPS Introduction](https://blog.vespa.ai/announcing-maximum-inner-product-search/)
[Blog Demonstrating the Application of MIPS](https://levelup.gitconnected.com/maximum-inner-product-mips-and-its-use-in-ml-2f3cd321150e)
[Y Combinator Hacker News Forum](https://news.ycombinator.com/item?id=35814381)
[Understanding the approximate nearest neighbor (ANN) algorithm](https://www.elastic.co/blog/understanding-ann)
[Faiss: A library for efficient similarity search](https://engineering.fb.com/2017/03/29/data-infrastructure/faiss-a-library-for-efficient-similarity-search/)

**Comment by parth126** [comment]
- Problem too broad and ambitious for a class project
- The problem could be narrowed down to optimizing a Vector retrieval setup by some approximate matching algorithms

**Comment by parth126** [comment]
The proposal is good enough for acceptance.
