### ISSUE TITLE
Real-Time Multi-Stream Data Summarization for Enhanced Crisis Response and Situational Awareness

### ISSUE THREAD

**Issue by 202103002** [parth126/IT550#14]
### Title

CrisisFACTS: Real-Time Multi-Stream Data Summarization for Enhanced Crisis Response and Situational Awareness

### Team Name

RescueRetrievers

### Email

202103015@daiict.ac.in

### Team Member 1 Name

Asish Joel Batha

### Team Member 1 Id

202103015

### Team Member 2 Name

Aadesh Minz

### Team Member 2 Id

202103002

### Team Member 3 Name

Raj Kariya 

### Team Member 3 Id

202103048

### Team Member 4 Name

NIL

### Team Member 4 Id

NIL

### Category

Evaluation Track Problem

### Problem Statement

The project aims to develop a system which enchances situational awareness during crisis by summarizing crucial real-time information from various data streams such as Twitter, Reddit, and Web News. The system will generate concise daily summaries of the most relevant facts, enabling local crisis response teams to access timely and relevant information, thereby improving disaster response coordination and decision-making.

### Evaluation Strategy

The project uses the Rouge Score and BERT-Score to evaluate the system's performance in generating summaries.

### Dataset

crisisFACTS - https://crisisfacts.github.io/

### Resources

CrisisFACTS overview paper - [https://crisisfacts.github.io/assets/pdf/crisisfacts2022.iscram2023.pdf](url)

Lin, C.-Y. (2004). ROUGE: A Package for Automatic Evaluation of Summaries. Proceedings of the Workshop on Text Summarization Branches Out.

Zhang, T., Kishore, V., Wu, F., et al. (2019). BERTScore: Evaluating Text Generation with BERT. arXiv preprint: [arXiv:1904.09675](https://arxiv.org/abs/1904.09675).

**Comment by parth126** [comment]
- Need more clarity on how the "real time" aspect will be simulated
- How will it be evaluated?

**Comment by 202103002** [comment]
Sir, so far we have come up with an appoach for simulating real time aspect in the project.

if we can divide the dataset into batches such that the new data will be appended incrementally after certain intervals. The system processes this data in batches, for each batch we use BM25 for retrieval and summarization models like BART or BERT for generating summaries and append the new summary into the existing one. After each batch, summaries are evaluated using ROUGE and BERT scores against golden summaries to track performance and relevance over time.

**Comment by parth126** [comment]
The team is required to identify a list of papers that use the crisisfact data and then narrow down to one paper
