### ISSUE TITLE
Text representation for direction prediction of share market

### ISSUE THREAD

**Issue by KunalAnand57** [parth126/IT550#18]
### Title
Text representation for direction prediction of share market

### Team Name
Stocks Savvy

### Email

202318035@daiict.ac.in

### Team Member 1 Name

Ashutosh Anand

### Team Member 1 Id

202318035

### Team Member 2 Name

Kunal Anand

### Team Member 2 Id

202318057

### Team Member 3 Name

Anjali Singh

### Team Member 3 Id

202318050

### Team Member 4 Name

NaN

### Team Member 4 Id

NaN

### Category
Reproducibility

### Problem Statement

The problem this study addresses is predicting the direction of stock market close price movement using financial news articles and historical price data. The study aims to investigate the impact of news articles on stock price movement and compare the effectiveness of using only historical prices, only news articles, and a combination of both.

### Evaluation Strategy

The evaluation strategy involves using accuracy, ROC-AUC, and normalized cross-correlation (NCC) to assess the performance of the prediction models. While accuracy measures the correct predictions, ROC-AUC captures the discriminative power, and NCC evaluates the correlation between predicted and actual time series with respect to time lags or leads.

### Dataset

https://drive.google.com/file/d/1BKMU6zvg_IDrxCC5a0tK2llc8I8J34qu/view

### Resources

https://www.sciencedirect.com/science/article/pii/S0957417422015561

**Comment by parth126** [comment]
- The project would boil down to making API calls, which is not sufficient
- Suggested a different topic. 
a.One possibility is stock prediction using textual data (e.g. news). This is under the condition that there exists a dataset that can be used for evaluation.

**Comment by parth126** [comment]
Advised to do this as a reproducibility experiment by implementing and building upon the paper by Ganguly et al.

**Comment by KunalAnand57** [comment]
Dear Sir,
We have updated our proposal idea as advised in the GitHub issue. Kindly review the changes at your convenience. Looking forward to your feedback .

**Comment by parth126** [comment]
Looks good
