### ISSUE TITLE
Fashion Product Retrieval Using Semantic Search and Natural Language Generation

### ISSUE THREAD

**Issue by KavishaMadani** [parth126/IT550#19]
### Title

Fashion Product Retrieval Using Semantic Search and Natural Language Generation

### Team Name

InfoSphere

### Email

202318007@daiict.ac.in

### Team Member 1 Name

Kavisha Madani

### Team Member 1 Id

202318007

### Team Member 2 Name

Vishaka Nair 

### Team Member 2 Id

202318041

### Team Member 3 Name

Srushti Bhagchandani

### Team Member 3 Id

202318047

### Team Member 4 Name

Shubham Gupta 

### Team Member 4 Id

202318052

### Category

Optimizing an existing system

### Problem Statement

This project aims to build a next-generation fashion product information retrieval and recommendation system by combining Natural Language Understanding (NLU) and semantic search techniques using advanced AI models like BERT and Sentence-BERT. The system will intelligently process user queries, detect their intent (e.g., event-based clothing recommendations like "traditional day" or "casual wear"), and identify relevant entities using NLU techniques. By leveraging neural search models and integrating generative AI (GenAI), the system will generate human-friendly, personalized responses while retrieving semantically aligned products from the H&M fashion dataset.

The project will further explore the integration of Large Language Models (LLMs) to enhance product recommendations, improving the user experience with personalized suggestions. This innovative approach has the potential to advance research in the AI/ML domain, making it suitable for publication in fashion technology or AI research journals.

### Evaluation Strategy

1. Retrieval Accuracy: Measure the accuracy of retrieved products in terms of relevance to the user query (using human evaluation or ground truth labels).
2. Response Quality: Evaluate the quality of the generated responses using metrics like BLEU score and user satisfaction surveys.
3. Latency: Measure the time taken for query processing, product retrieval, and response generation.

### Dataset

H&M Fashion Dataset

### Resources

https://medium.com/@kumawatayushi31/heuristic-evaluation-for-fashion-gpt-on-myntra-a-ux-case-study-a5b4b70006a

**Comment by parth126** [comment]
- Find a clustering dataset. Should be large enough, should have topic labels.
- RAG part is unnecessary. This could be a simple topic modelling project
