### ISSUE TITLE
Embedding based approach over Traditional LDA for AdHoc Retrieval

### ISSUE THREAD

**Issue by bhavan-bhatt** [parth126/IT550#20]
### Title

Embedding based approach over Traditional LDA for AdHoc Retrieval

### Team Name

Retrieval Kings

### Email

202311021@daiict.ac.in

### Team Member 1 Name

Bhavan Bhatt

### Team Member 1 Id

202311021

### Team Member 2 Name

Ayush Hirdani

### Team Member 2 Id

202101139

### Team Member 3 Name

Harshneel Soni

### Team Member 3 Id

202311024

### Team Member 4 Name

Samarth Motka

### Team Member 4 Id

202311023

### Category

Reproducibility

### Problem Statement

Existing systems utilising LDA for ad-hoc retrieval only look at words on a global level, there have been improvements on it using Word2Vec we intend on reproducing the results and then improving it by using other techniques.

### Evaluation Strategy

MAP, GMAP and Recall 

### Dataset

Robust - https://trec.nist.gov/data/robust/04.guidelines.html

### Resources

Title - LDA-Based Document Models for Ad-hoc Retrieval 
Link - https://dl.acm.org/doi/10.1145/1148170.1148204

Title - A Word Embedding based Generalized Language Model for
Information Retrieval
Link - https://dl.acm.org/doi/10.1145/2766462.2767780

**Comment by parth126** [comment]
- Problem needs to be a little deeper (try modifying the approach in some manner) or broader (experiment with more language models)
