### ISSUE TITLE
 Summarization-based Query Expansion in Information Retrieval

### ISSUE THREAD

**Issue by kanishk231102** [parth126/IT550#25]
### Title

 Summarization-based Query Expansion in Information Retrieval

### Team Name

One man army

### Email

202101134@daiict.ac.in

### Team Member 1 Name

Kanishk Pareek

### Team Member 1 Id

202101134

### Team Member 2 Name

-

### Team Member 2 Id

-

### Team Member 3 Name

-

### Team Member 3 Id

-

### Team Member 4 Name

-

### Team Member 4 Id

-

### Category

Reproducibility

### Problem Statement

Building more effective search queries for information retrieval systems.

### Evaluation Strategy

1. Original queries vs expanded queries.
2. NLIR system vs SMART system (used as a benchmark).

### Dataset

~TFtEC-6 database consisted of approx. 2 GBytes of documents from Associated Press newswire, Wall Street Journal, Financial Times, Federal Keglster, FBIS and other sources (Haxman & Voorhees 1998).

### Resources

https://aclanthology.org/P98-2205.pdf

**Comment by parth126** [comment]
The proposal was withdrawn
