### ISSUE TITLE
Document Ranking with a Pretrained Sequence-to-Sequence Model

### ISSUE THREAD

**Issue by pratham4521** [parth126/IT550#4]
### Title

Document Ranking with a Pretrained Sequence-to-Sequence Model

### Team Name

Team DSSM

### Email

202311022@daiict.ac.in

### Team Member 1 Name

Pratham Patel

### Team Member 1 Id

202311022

### Team Member 2 Name

Nishit Munjani

### Team Member 2 Id

202311026

### Team Member 3 Name

Rohit Rathod

### Team Member 3 Id

202311039

### Team Member 4 Name

Ayushi Mehta

### Team Member 4 Id

202311008

### Category

Reproducibility

### Problem Statement

The project is aimed to re-rank the documents using pre-trained models like T5. 

### Evaluation Strategy

MRR@10

### Dataset

Ms-Marco - https://microsoft.github.io/msmarco/Datasets.html

### Resources

Document Ranking with a Pretrained Sequence-to-Sequence Model
Arxiv : https://arxiv.org/abs/2003.06713

**Comment by parth126** [comment]
- Unclear if the proposed dataset is usable for the given task. 
- Suggested to verify the following:
a. Understand the dataset and how relevance is computed for it. 
b. Do a feasibility test (by comparing existing implementation with tf-idf for example) to ensure this project is actually viable

**Comment by pratham4521** [comment]
Respected sir, due to the large size of standard datasets we did not have enough time to train pre-implemented models on these datasets. Therefore we decided to change the topic for our project.

**Comment by parth126** [comment]
Include the reference paper in the proposal. 
Task is reranking using T5 on Trec robust and MS Marco datasets.
