### ISSUE TITLE
NER on patent data

### ISSUE THREAD

**Issue by aditi092001** [parth126/IT550#6]
### Title

NER on patent data

### Team Name

Octane

### Email

202318005@daiict.ac.in

### Team Member 1 Name

Aditi singh

### Team Member 1 Id

202318005

### Team Member 2 Name

Hani Soni

### Team Member 2 Id

202318044

### Team Member 3 Name

Kruti patel

### Team Member 3 Id

202318032

### Team Member 4 Name

Garvika singh rajawat

### Team Member 4 Id

202318061

### Category

Optimizing an existing system

### Problem Statement

We are going to do Named Entity Recognition on the solar patent data which we are going to scrape from Google patents based on different solar modules, technology, material and innovation. We are then going to train a patentBert based on the initial few annotations we make on the collected data for NER task.

### Evaluation Strategy

We are yet to decide on the evaluation strategy.

### Dataset

Not yet

### Resources

https://arxiv.org/abs/1901.08746

**Comment by parth126** [comment]
- Outcomes: A new dataset for NER on solar patents + understanding and implementing a NER model
- Data can be generated using a mix of human labels and LLMs
- Recommended doing all experiments on an additional known dataset. This will help in a fair evaluation. 
- Atleast one NER needs to be implemented from scratch. Only training the models within exisitng tools like spacy is not sufficient.

**Comment by parth126** [comment]
Paper template needs to be corrected.

**Comment by aditi092001** [comment]
Have made the changes sir.
