### ISSUE TITLE
Building a Question Answering (QA) system using BERT

### ISSUE THREAD

**Issue by gokublacko7** [parth126/IT550#8]
### Title

A quantum-inspired sentiment representation model 

### Team Name

Noah

### Email

202311016@daiict.ac.in

### Team Member 1 Name

Harsh Vyas

### Team Member 1 Id

202311015

### Team Member 2 Name

Birva Oza

### Team Member 2 Id

202311050

### Team Member 3 Name

Parshwa Dand

### Team Member 3 Id

202311016

### Team Member 4 Name

Darshit Kalariya

### Team Member 4 Id

202311035

### Category

reproductivity

### Problem Statement

Preprocessing: Text cleaning, spelling correction, removal of stop words, and tokenization using HMM-based part-of-speech tagging.
Embedding Generation: The model uses word embeddings to represent words in a vector space. These embeddings are trained using the Gensim API with a dimension of 100.
Classifier Training: Three machine-learning classifiers were used: Naive Bayes (NB), Support Vector Machine (SVM), and Random Forest (RF). Additionally, deep learning models like CNN, LSTM, and fully connected deep neural networks (FCDNN) were employed​

### Evaluation Strategy

To evaluate the overall classification performance of each methods accuracy, precision, recall, and F1 score will be used

### Dataset

Obama-McCain Debate (OMD) dataset and the Sentiment140 Twitter dataset

### Resources

https://link.springer.com/article/10.1007/s10489-019-01441-4

**Comment by parth126** [comment]
Deliverables are not clear: 
- Expected outcome is implementing this from scratch without use of existing github repos and huggingface. 
- Evaluation will be based on understanding of the code and how well the trained model performs

**Comment by gokublacko7** [comment]
A quantum-inspired sentiment representation model for twitter sentiment analysis

**Comment by parth126** [comment]
The team will use QSR model for classification task on several datasets.
It will be compared to other baseline models (e.g. VM, NB RF)
